# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-29 18:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0005_auto_20160127_1936'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='relayed_addr_cnt',
            field=models.CharField(default='1', max_length=100),
        ),
    ]
