# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-30 05:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0007_relayaddress'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='relayed_addr',
        ),
        migrations.RemoveField(
            model_name='address',
            name='relayed_addr_cnt',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='relay_limit',
            field=models.CharField(default=2, max_length=140),
        ),
    ]
